[package]
name = "pas_backend_c"
version = "0.1.0"
authors = ["spriest487 <spriest487@googlemail.com>"]
edition = "2021"

[dependencies]
pas_ir = { path = "../intermediate" }
pas_common = { path = "../common" }

topological-sort = "0.1.0"
