[package]
name = "backend_c"
version = "0.1.0"
authors = ["spriest487 <spriest487@googlemail.com>"]
edition = "2021"

[dependencies]
common = { path = "../common" }
terapascal-ir = { path = "../ir" }

topological-sort = "0.2.2"
