[package]
name = "backend_c"
version = "0.1.0"
authors = ["spriest487 <spriest487@googlemail.com>"]
edition = "2021"

[dependencies]
intermediate = { path = "../intermediate" }
common = { path = "../common" }

topological-sort = "0.1.0"
