[package]
name = "terapascal-backend-c"
version = "0.1.0"
authors = ["spriest487 <spriest487@googlemail.com>"]
edition = "2024"

[dependencies]
terapascal-common = { path = "../common" }
terapascal-ir = { path = "../ir" }

topological-sort = "0.2.2"
