edition = "2024"
imports_layout = "Vertical"
imports_granularity = "Item"
reorder_imports = true
reorder_modules = true
normalize_comments = true
match_block_trailing_comma = true
match_arm_leading_pipes = "Preserve"
empty_item_single_line = false
max_width = 100
chain_width = 100
array_width = 100
comment_width = 100
overflow_delimited_expr = true
use_field_init_shorthand = true
