[package]
name = "pas_syn"
version = "0.1.0"
authors = ["spriest487 <spriest487@googlemail.com>"]
edition = "2021"

[dependencies]
pas_common = { path = "../pas_common" }
pas_pp = { path = "../pas_pp" }
bigdecimal = "0.0.14"
cast = "0.3.0"
derivative = "2.2.0"
linked-hash-map = "0.5.4"
