[package]
name = "pas_backend_c"
version = "0.1.0"
authors = ["spriest487 <spriest487@googlemail.com>"]
edition = "2021"

[dependencies]
pas_ir = { path = "../pas_ir" }
pas_common = { path = "../pas_common" }

topological-sort = "0.1.0"
