[package]
name = "pas_backend_c"
version = "0.1.0"
authors = ["Simon Priest <simon@westpierstudio.com>"]
edition = "2018"

[dependencies]
pas_ir = { path = "../pas_ir" }
pas_common = { path = "../pas_common" }

topological-sort = "0.1.0"