[package]
name = "intermediate"
version = "0.1.0"
authors = ["spriest487 <spriest487@googlemail.com>"]
edition = "2021"

[dependencies]
common = { path = "../common" }
frontend = { path = "../frontend" }
ir-lang = { path = "../ir_lang" }
linked-hash-map = "0.5.2"
cast = "0.3.0"
bigdecimal = "0.4.5"
