[package]
name = "pas_ir"
version = "0.1.0"
authors = ["spriest487 <spriest487@googlemail.com>"]
edition = "2018"

[dependencies]
pas_common = { path = "../pas_common" }
pas_syn = { path = "../pas_syn" }
pas_typecheck = { path = "../pas_typecheck" }
linked-hash-map = "0.5.2"