[package]
name = "pas_interpreter"
version = "0.1.0"
authors = ["spriest487 <spriest487@googlemail.com>"]
edition = "2021"

[dependencies]
pas_ir = { path = "../pas_ir" }
pas_common = { path = "../pas_common" }
libffi = "2.0.0"
dlopen = "0.1.8"
cast = "0.3.0"
smallvec = "1.8.0"
